Repository EnF-EEEEEE/BackEnd, pull requests merged in 2025-04, with the labels that each got.

#100 Dear 123 버디테스트 수정 api 개발
  EnF/module-api/src/main/java/com/enf/api/component/facade/UserFacade.java
  EnF/module-api/src/main/java/com/enf/api/controller/UserController.java
  EnF/module-api/src/main/java/com/enf/api/service/UserService.java
  EnF/module-api/src/main/java/com/enf/api/service/impl/BirdyServiceImpl.java
  EnF/module-api/src/main/java/com/enf/api/service/impl/UserServiceImpl.java
  EnF/module-domain/src/main/java/com/enf/domain/model/type/FailedResultType.java
  EnF/module-domain/src/main/java/com/enf/domain/model/type/SuccessResultType.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/BirdRepository.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/UserRepository.java
Labels: feat

#101 feat : 편지 전송 알고리즘 개선
  EnF/module-domain/src/main/java/com/enf/domain/repository/querydsl/UserQueryRepository.java
Labels: refactor

#102 Dear 126 문의하기 api 확인
  EnF/module-api/src/main/java/com/enf/api/component/KakaoAuthHandler.java
  EnF/module-api/src/main/java/com/enf/api/controller/AdminController.java
  EnF/module-api/src/main/java/com/enf/api/controller/AuthController.java
  EnF/module-api/src/main/java/com/enf/api/controller/InquiryController.java
  EnF/module-api/src/main/java/com/enf/api/service/InquiryService.java
  EnF/module-api/src/main/java/com/enf/api/service/impl/InquiryServiceImpl.java
  EnF/module-api/src/main/resources/templates/admin/dashboard.html
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/inquiry/InquiryDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/inquiry/InquiryDetailDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/inquiry/InquiryListDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/inquiry/InquiryPageResponseDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/inquiry/InquiryResponseDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/response/inquiry/CreateInquiryResponseDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/response/inquiry/InquiryResponseResultDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/type/FailedResultType.java
  EnF/module-domain/src/main/java/com/enf/domain/model/type/SuccessResultType.java
Labels: refactor

#103 Dear 122 욕설 필터링 기능
  EnF/module-api/src/main/java/com/enf/api/component/badword/BadWordAspect.java
  EnF/module-api/src/main/java/com/enf/api/component/badword/BadWordConfig.java
  EnF/module-api/src/main/java/com/enf/api/component/badword/BadWordExceptionDTO.java
  EnF/module-api/src/main/java/com/enf/api/component/badword/BadWordFiltering.java
  EnF/module-api/src/main/java/com/enf/api/component/badword/BadWords.java
  EnF/module-api/src/main/java/com/enf/api/component/badword/annotation/BadWordCheck.java
  EnF/module-api/src/main/java/com/enf/api/controller/InquiryController.java
  EnF/module-api/src/main/java/com/enf/api/controller/LetterController.java
  EnF/module-api/src/main/java/com/enf/api/controller/UserController.java
  EnF/module-api/src/main/java/com/enf/api/exception/GlobalException.java
  EnF/module-domain/src/main/java/com/enf/domain/model/type/FailedResultType.java
Labels: feat

#105 Dear 136 공지사항 관련 기능 개발
  EnF/module-api/src/main/java/com/enf/api/config/SecurityConfig.java
  EnF/module-api/src/main/java/com/enf/api/controller/AnnouncementsController.java
  EnF/module-api/src/main/java/com/enf/api/service/AnnouncementsService.java
  EnF/module-api/src/main/java/com/enf/api/service/impl/AnnouncementsServiceImpl.java
  EnF/module-domain/src/main/java/com/enf/domain/entity/AnnouncementsEntity.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/announcements/AnnouncementsDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/response/announcements/Announcements.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/response/announcements/AnnouncementsDetails.java
  EnF/module-domain/src/main/java/com/enf/domain/model/type/AnnouncementsType.java
  EnF/module-domain/src/main/java/com/enf/domain/model/type/FailedResultType.java
  EnF/module-domain/src/main/java/com/enf/domain/model/type/SuccessResultType.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/AnnouncementsRepository.java
Labels: feat

#104 DEAR-133 feat : mail 전송 모듈 개발
  EnF/module-api/build.gradle
  EnF/module-api/src/main/java/com/enf/api/config/FeignClientConfig.java
  EnF/module-api/src/main/java/com/enf/api/config/FeignConfig.java
  EnF/module-api/src/main/java/com/enf/api/feign/EmailFeignClient.java
  EnF/module-api/src/main/java/com/enf/api/service/EmailService.java
  EnF/module-api/src/main/java/com/enf/api/service/impl/EmailServiceImpl.java
  EnF/module-api/src/main/java/com/enf/api/service/impl/LetterServiceImpl.java
  EnF/module-api/src/main/resources/application-dev.yml
  EnF/module-api/src/main/resources/application-prod.yml
  EnF/module-domain/src/main/java/com/enf/domain/entity/EmailLogEntity.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/email/SendEmailDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/EmailLogRepository.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/querydsl/UserQueryRepository.java
  EnF/module-email/build.gradle
  EnF/module-email/http/email.http
  EnF/module-email/src/main/java/com/enf/email/EmailApplication.java
  EnF/module-email/src/main/java/com/enf/email/config/AsyncConfig.java
  EnF/module-email/src/main/java/com/enf/email/config/EmailConfig.java
  EnF/module-email/src/main/java/com/enf/email/config/WebConfig.java
  EnF/module-email/src/main/java/com/enf/email/controller/EmailController.java
  EnF/module-email/src/main/java/com/enf/email/interceptor/ApiKeyInterceptor.java
  EnF/module-email/src/main/java/com/enf/email/service/EmailService.java
  EnF/module-email/src/main/java/com/enf/email/service/impl/EmailServiceImpl.java
  EnF/module-email/src/main/resources/application-dev.yml
  EnF/module-email/src/main/resources/application-prod.yml
  EnF/module-email/src/main/resources/application.yml
  EnF/module-email/src/main/resources/templates/email/mentee-letter-arrived.html
  EnF/module-email/src/main/resources/templates/email/mentor-letter-arrived.html
  EnF/module-email/src/main/resources/templates/email/one-day-notice.html
  EnF/settings.gradle
Labels: feat

#106 Dear 138 회원탈퇴 api 수정
  EnF/module-api/src/main/java/com/enf/api/component/facade/UserFacade.java
  EnF/module-api/src/main/java/com/enf/api/controller/AuthController.java
  EnF/module-api/src/main/java/com/enf/api/service/AuthService.java
  EnF/module-api/src/main/java/com/enf/api/service/impl/AuthServiceImpl.java
  EnF/module-domain/src/main/java/com/enf/domain/entity/WithdrawalEntity.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/auth/WithdrawalDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/type/WithdrawalType.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/WithdrawalRepository.java
Labels: feat

#111 110 fix 회원탈퇴 api 수정
  EnF/module-api/src/main/java/com/enf/api/controller/AuthController.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/UserRepository.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/WithdrawalRepository.java
  docker-compose.yml
Labels: bug

#112 DEAR-141 docker container간 통신이 되지 않는 문제 해결
  EnF/module-api/src/main/java/com/enf/api/feign/EmailFeignClient.java
Labels: bug

#113 Dear 142 spring batch 작업
  EnF/.gitignore
  EnF/module-api/src/main/java/com/enf/api/component/facade/LetterFacade.java
  EnF/module-api/src/main/java/com/enf/api/component/facade/UserFacade.java
  EnF/module-api/src/main/java/com/enf/api/config/SchedulerConfiguration.java
  EnF/module-api/src/main/java/com/enf/api/config/SecurityConfig.java
  EnF/module-api/src/main/java/com/enf/api/controller/BatchController.java
  EnF/module-api/src/main/java/com/enf/api/service/BatchService.java
  EnF/module-api/src/main/java/com/enf/api/service/impl/BatchServiceImpl.java
  EnF/module-batch/build.gradle
  EnF/module-batch/src/main/java/com/enf/batch/BatchApplication.java
  EnF/module-batch/src/main/java/com/enf/batch/config/BatchConfig.java
  EnF/module-batch/src/main/java/com/enf/batch/config/JobExecutionHolder.java
  EnF/module-batch/src/main/java/com/enf/batch/config/RestTemplateConfig.java
  EnF/module-batch/src/main/java/com/enf/batch/job/DailyJobConfiguration.java
  EnF/module-batch/src/main/java/com/enf/batch/job/WeeklyJobConfiguration.java
  EnF/module-batch/src/main/java/com/enf/batch/reader/UnansweredLettersReader.java
  EnF/module-batch/src/main/java/com/enf/batch/reader/UserQuotaReader.java
  EnF/module-batch/src/main/java/com/enf/batch/reader/WithdrawalUserReader.java
  EnF/module-batch/src/main/java/com/enf/batch/writer/UnansweredLettersWriter.java
  EnF/module-batch/src/main/java/com/enf/batch/writer/UserQuotaWriter.java
  EnF/module-batch/src/main/java/com/enf/batch/writer/WithdrawalUserWriter.java
  EnF/module-batch/src/main/resources/application-dev.yml
  EnF/module-batch/src/main/resources/application-prod.yml
  EnF/module-batch/src/main/resources/application.yml
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/notification/BatchNotificationDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/request/notification/NotificationDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/model/dto/response/letter/UnansweredLetterDTO.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/LetterRepository.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/LetterStatusRepository.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/NotificationRepository.java
  EnF/module-domain/src/main/java/com/enf/domain/repository/UserRepository.java
Labels: feat

#114 Dear 143 프로젝트 최소화
  EnF/build.gradle
  EnF/module-api/build.gradle
  EnF/module-api/src/main/java/com/enf/api/config/MetricsConfig.java
  EnF/module-api/src/main/java/com/enf/api/service/impl/LetterServiceImpl.java
  EnF/module-api/src/main/resources/application-dev.yml
  EnF/module-api/src/main/resources/application-prod.yml
  EnF/module-api/src/main/resources/logback-spring.xml
  docker-compose.yml
  logstash/config/logstash.yml
  logstash/pipeline/logstash.conf
  prometheus.yml
Labels: chore
