Repository EnF-EEEEEE/BackEnd, pull requests merged in 2025-03, with the labels that each got.

#37 [feat] 편지 답장 기능 구현
  EnF/src/main/java/com/enf/component/facade/UserFacade.java
  EnF/src/main/java/com/enf/controller/LetterController.java
  EnF/src/main/java/com/enf/model/dto/request/letter/ReceiveLetterDTO.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/repository/UserRepository.java
  EnF/src/main/java/com/enf/service/LetterService.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
Labels: feat

#41 [refactor] 편지 Entity 수정 및 관련 로직 수정
  EnF/src/main/java/com/enf/component/facade/LetterFacade.java
  EnF/src/main/java/com/enf/component/facade/UserFacade.java
  EnF/src/main/java/com/enf/controller/LetterController.java
  EnF/src/main/java/com/enf/entity/LetterEntity.java
  EnF/src/main/java/com/enf/model/dto/request/letter/ReplyLetterDTO.java
  EnF/src/main/java/com/enf/model/dto/request/letter/SendLetterDTO.java
  EnF/src/main/java/com/enf/model/dto/request/notification/NotificationDTO.java
  EnF/src/main/java/com/enf/model/type/FailedResultType.java
  EnF/src/main/java/com/enf/repository/LetterRepository.java
  EnF/src/main/java/com/enf/repository/querydsl/UserQueryRepository.java
  EnF/src/main/java/com/enf/service/LetterService.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
Labels: refactor

#43 [feat] 편지 저장, 저장한 편지 조회, 편지 상세정보 조회 API 구현
  EnF/src/main/java/com/enf/component/facade/LetterFacade.java
  EnF/src/main/java/com/enf/controller/LetterController.java
  EnF/src/main/java/com/enf/entity/LetterEntity.java
  EnF/src/main/java/com/enf/entity/LetterStatusEntity.java
  EnF/src/main/java/com/enf/model/dto/request/letter/ReplyLetterDTO.java
  EnF/src/main/java/com/enf/model/dto/request/letter/SendLetterDTO.java
  EnF/src/main/java/com/enf/model/dto/response/letter/LetterDTO.java
  EnF/src/main/java/com/enf/model/dto/response/letter/LetterDetailsDTO.java
  EnF/src/main/java/com/enf/model/dto/response/letter/ReceiveLetterDTO.java
  EnF/src/main/java/com/enf/model/dto/response/user/UserInfoDTO.java
  EnF/src/main/java/com/enf/model/type/LetterListType.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/repository/LetterRepository.java
  EnF/src/main/java/com/enf/repository/LetterStatusRepository.java
  EnF/src/main/java/com/enf/repository/querydsl/LetterQueryRepository.java
  EnF/src/main/java/com/enf/service/LetterService.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
Labels: feat, refactor

#45 [feat] 편지 저장 쿼리문 수정
  EnF/src/main/java/com/enf/config/JwtTokenFilter.java
  EnF/src/main/java/com/enf/repository/LetterStatusRepository.java
Labels: refactor

#52 [feat] 고마움 전달하기 API 구현
  EnF/src/main/java/com/enf/component/facade/LetterFacade.java
  EnF/src/main/java/com/enf/config/JwtTokenFilter.java
  EnF/src/main/java/com/enf/config/SecurityConfig.java
  EnF/src/main/java/com/enf/controller/LetterController.java
  EnF/src/main/java/com/enf/entity/LetterStatusEntity.java
  EnF/src/main/java/com/enf/model/dto/request/notification/NotificationDTO.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/repository/LetterStatusRepository.java
  EnF/src/main/java/com/enf/service/LetterService.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
Labels: feat

#54 [refactor] 알림 전달 방식 String -> Object 형식으로 변경
  EnF/src/main/java/com/enf/component/facade/LetterFacade.java
  EnF/src/main/java/com/enf/entity/NotificationEntity.java
  EnF/src/main/java/com/enf/model/dto/request/notification/NotificationDTO.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/NotificationServiceImpl.java
Labels: refactor

#50 [feat] CORS 정책 설정을 위한 CorsConfig 클래스 구현
  EnF/src/main/java/com/enf/config/CorsConfig.java
  EnF/src/main/java/com/enf/model/type/UrlType.java
Labels: feat

#56 [feat] 관리자 기능 : 카테고리별 넘긴 편지 개수 확인 API 구현
  EnF/src/main/java/com/enf/component/facade/LetterFacade.java
  EnF/src/main/java/com/enf/controller/LetterController.java
  EnF/src/main/java/com/enf/entity/ThrowLetterCategoryEntity.java
  EnF/src/main/java/com/enf/model/dto/response/letter/ThrowLetterCategoryDTO.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/repository/ThrowLetterCategoryRepository.java
  EnF/src/main/java/com/enf/repository/querydsl/LetterQueryRepository.java
  EnF/src/main/java/com/enf/service/LetterService.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
Labels: feat

#58 [feat] 전반적인 리페토링
  EnF/src/main/java/com/enf/EnFApplication.java
  EnF/src/main/java/com/enf/component/KakaoAuthHandler.java
  EnF/src/main/java/com/enf/component/facade/LetterFacade.java
  EnF/src/main/java/com/enf/component/facade/UserFacade.java
  EnF/src/main/java/com/enf/config/SchedulerConfiguration.java
  EnF/src/main/java/com/enf/config/SecurityConfig.java
  EnF/src/main/java/com/enf/config/SecurityConstants.java
  EnF/src/main/java/com/enf/controller/AuthController.java
  EnF/src/main/java/com/enf/entity/LetterStatusEntity.java
  EnF/src/main/java/com/enf/entity/UserEntity.java
  EnF/src/main/java/com/enf/model/type/FailedResultType.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/model/type/UrlType.java
  EnF/src/main/java/com/enf/repository/QuotaRepository.java
  EnF/src/main/java/com/enf/repository/UserRepository.java
  EnF/src/main/java/com/enf/service/AuthService.java
  EnF/src/main/java/com/enf/service/impl/AuthServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
Labels: refactor

#59 Feat/#34/admin inquiry
  EnF/build.gradle
  EnF/src/main/java/com/enf/component/KakaoAuthHandler.java
  EnF/src/main/java/com/enf/component/facade/UserFacade.java
  EnF/src/main/java/com/enf/config/AdminConfig.java
  EnF/src/main/java/com/enf/config/SecurityConstants.java
  EnF/src/main/java/com/enf/controller/AdminController.java
  EnF/src/main/java/com/enf/controller/AdminViewController.java
  EnF/src/main/java/com/enf/controller/AuthController.java
  EnF/src/main/java/com/enf/controller/InquiryController.java
  EnF/src/main/java/com/enf/controller/ReportController.java
  EnF/src/main/java/com/enf/entity/InquiryEntity.java
  EnF/src/main/java/com/enf/entity/InquiryResponseEntity.java
  EnF/src/main/java/com/enf/entity/LetterEntity.java
  EnF/src/main/java/com/enf/entity/LetterStatusEntity.java
  EnF/src/main/java/com/enf/entity/ReportEntity.java
  EnF/src/main/java/com/enf/entity/ReportProcessEntity.java
  EnF/src/main/java/com/enf/entity/ThrowLetterEntity.java
  EnF/src/main/java/com/enf/model/dto/request/report/ReportDto.java
  EnF/src/main/java/com/enf/model/dto/response/letter/LetterDetailResponseDto.java
  EnF/src/main/java/com/enf/model/dto/response/letter/LetterResponseDto.java
  EnF/src/main/java/com/enf/model/type/ReportCategory.java
  EnF/src/main/java/com/enf/model/type/ReportStatus.java
  EnF/src/main/java/com/enf/repository/InquiryRepository.java
  EnF/src/main/java/com/enf/repository/InquiryResponseRepository.java
  EnF/src/main/java/com/enf/repository/LetterStatusRepository.java
  EnF/src/main/java/com/enf/repository/ReportProcessRepository.java
  EnF/src/main/java/com/enf/repository/ReportRepository.java
  EnF/src/main/java/com/enf/repository/UserRepository.java
  EnF/src/main/java/com/enf/repository/querydsl/LetterAppreciationQueryRepository.java
  EnF/src/main/java/com/enf/repository/querydsl/LetterQueryRepository.java
  EnF/src/main/java/com/enf/repository/querydsl/LetterQueryStatusRepository.java
  EnF/src/main/java/com/enf/repository/querydsl/UserConversionQueryRepository.java
  EnF/src/main/java/com/enf/repository/querydsl/UserQueryRepository.java
  EnF/src/main/java/com/enf/service/AdminService.java
  EnF/src/main/java/com/enf/service/AuthService.java
  EnF/src/main/java/com/enf/service/ChurnAnalysisService.java
  EnF/src/main/java/com/enf/service/InquiryService.java
  EnF/src/main/java/com/enf/service/LetterService.java
  EnF/src/main/java/com/enf/service/ReportService.java
  EnF/src/main/java/com/enf/service/UserConversionService.java
  EnF/src/main/java/com/enf/service/impl/AdminServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/AuthServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/ChurnAnalysisServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/InquiryServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/ReportServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/UserConversionServiceImpl.java
  EnF/src/main/resources/application-dev.yml
  EnF/src/main/resources/application-prod.yml
  EnF/src/main/resources/static/favicon.ico
  EnF/src/main/resources/templates/admin/dashboard.html
  EnF/src/main/resources/templates/admin/inquiries.html
  EnF/src/main/resources/templates/admin/inquiry-detail.html
  EnF/src/main/resources/templates/admin/login.html
  EnF/src/test/java/com/enf/auth/AuthServiceImplTest.java
Labels: feat

#61 [feat] 새 유형 관련 API 구현
  EnF/src/main/java/com/enf/config/SecurityConstants.java
  EnF/src/main/java/com/enf/controller/BirdyController.java
  EnF/src/main/java/com/enf/entity/BirdEntity.java
  EnF/src/main/java/com/enf/model/dto/response/bird/BirdExplanationDTO.java
  EnF/src/main/java/com/enf/model/dto/response/bird/BirdyListDTO.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/service/BirdyService.java
  EnF/src/main/java/com/enf/service/impl/BirdyServiceImpl.java
Labels: feat

#66 [refactor] 편지 고마움 전달 API 로직 수정
  EnF/src/main/java/com/enf/component/facade/LetterFacade.java
  EnF/src/main/java/com/enf/controller/LetterController.java
  EnF/src/main/java/com/enf/entity/LetterStatusEntity.java
  EnF/src/main/java/com/enf/model/dto/response/letter/LetterDetailsDTO.java
  EnF/src/main/java/com/enf/model/dto/response/letter/ReceiveLetterDTO.java
  EnF/src/main/java/com/enf/model/type/ThanksType.java
  EnF/src/main/java/com/enf/repository/LetterStatusRepository.java
  EnF/src/main/java/com/enf/service/LetterService.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
Labels: refactor

#67 feat/#62/report-sanction
  EnF/src/main/java/com/enf/component/facade/LetterFacade.java
  EnF/src/main/java/com/enf/config/CorsConfig.java
  EnF/src/main/java/com/enf/controller/ReportController.java
  EnF/src/main/java/com/enf/entity/LetterStatusEntity.java
  EnF/src/main/java/com/enf/entity/PenaltyEntity.java
  EnF/src/main/java/com/enf/entity/ReportProcessEntity.java
  EnF/src/main/java/com/enf/entity/UserEntity.java
  EnF/src/main/java/com/enf/model/type/FailedResultType.java
  EnF/src/main/java/com/enf/model/type/PenaltyType.java
  EnF/src/main/java/com/enf/model/type/ReportStatus.java
  EnF/src/main/java/com/enf/repository/PenaltyRepository.java
  EnF/src/main/java/com/enf/service/impl/ReportServiceImpl.java
  EnF/src/main/resources/templates/admin/dashboard.html
Labels: feat

#71 Feat/#70/monitering
  EnF/build.gradle
  EnF/src/main/java/com/enf/config/MetricsConfig.java
  EnF/src/main/java/com/enf/config/RequestLoggingFilterConfig.java
  EnF/src/main/java/com/enf/config/SecurityConfig.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
  EnF/src/main/resources/application-dev.yml
  EnF/src/main/resources/application-prod.yml
  EnF/src/main/resources/logback-spring.xml
  docker-compose.yml
  prometheus.yml
Labels: chore

#74 Chore/#73/change admin redirect url
  EnF/src/main/java/com/enf/component/KakaoAuthHandler.java
  EnF/src/main/java/com/enf/config/SecurityConfig.java
  EnF/src/main/java/com/enf/controller/AdminViewController.java
Labels: chore

#82 chore : add Linux OS setting
  docker-compose.yml
Labels: chore

#86 [refactor] 카카로 로그인 API 수정 및 사용하지 않은 API 삭제
  EnF/src/main/java/com/enf/component/facade/UserFacade.java
  EnF/src/main/java/com/enf/controller/LetterController.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/service/LetterService.java
  EnF/src/main/java/com/enf/service/impl/AuthServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
Labels: refactor

#88 refactor : change NotificationDTO send,replyLetter text message
  EnF/src/main/java/com/enf/model/dto/request/notification/NotificationDTO.java
Labels: refactor

#90 fix : 남은 편지 개수가 0개 일경우 예외처리 로직 추가
  EnF/src/main/java/com/enf/component/facade/UserFacade.java
  EnF/src/main/java/com/enf/model/type/FailedResultType.java
  EnF/src/main/java/com/enf/repository/QuotaRepository.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
Labels: bug
