Repository EnF-EEEEEE/BackEnd, pull requests merged in 2025-02, with the labels that each got.

#2 [chore] docker setting
  EnF/.gitignore
  EnF/Dockerfile
  EnF/src/main/resources/application-dev.yml
  EnF/src/main/resources/application-prod.yml
  EnF/src/main/resources/application.properties
  EnF/src/main/resources/application.yml
  data/mysql/env.mysql
  docker-compose.yml
Labels: chore

#8 [feat] Swagger Setting
  EnF/build.gradle
  EnF/src/main/java/com/enf/config/SwaggerConfig.java
Labels: feat

#14 [feat] 커스텀 예외 처리클래스 및 요청에 대한 응답 클래스 구현
  EnF/src/main/java/com/enf/exception/GlobalException.java
  EnF/src/main/java/com/enf/exception/GlobalExceptionHandler.java
  EnF/src/main/java/com/enf/model/dto/response/ResultResponse.java
  EnF/src/main/java/com/enf/model/type/FailedResultType.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
Labels: feat

#16 [feat] 닉네임 중복 검증 API 구현
  EnF/build.gradle
  EnF/src/main/java/com/enf/controller/UserController.java
  EnF/src/main/java/com/enf/entity/UserEntity.java
  EnF/src/main/java/com/enf/model/type/RoleType.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/repository/UserRepository.java
  EnF/src/main/java/com/enf/service/UserService.java
  EnF/src/main/java/com/enf/service/impl/UserServiceImpl.java
  EnF/src/test/java/com/enf/service/impl/UserServiceImplTest.java
Labels: feat

#18 [refactor] 사용자 역할(Role) 관리 방식 수정
  EnF/src/main/java/com/enf/entity/RoleEntity.java
  EnF/src/main/java/com/enf/entity/UserEntity.java
  EnF/src/main/java/com/enf/model/type/RoleType.java
Labels: refactor

#4 [feat] 카카오 로그인 기능 구현
  EnF/build.gradle
  EnF/src/main/java/com/enf/EnFApplication.java
  EnF/src/main/java/com/enf/component/KakaoAuthHandler.java
  EnF/src/main/java/com/enf/config/SecurityConfig.java
  EnF/src/main/java/com/enf/config/SecurityConstants.java
  EnF/src/main/java/com/enf/controller/AuthController.java
  EnF/src/main/java/com/enf/entity/UserEntity.java
  EnF/src/main/java/com/enf/model/dto/request/auth/KakaoUserDetailsDTO.java
  EnF/src/main/java/com/enf/model/dto/response/ResultResponse.java
  EnF/src/main/java/com/enf/model/type/FailedResultType.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/model/type/UrlType.java
  EnF/src/main/java/com/enf/repository/UserRepository.java
  EnF/src/main/java/com/enf/service/AuthService.java
  EnF/src/main/java/com/enf/service/impl/AuthServiceImpl.java
  EnF/src/main/resources/application-dev.yml
  EnF/src/main/resources/application-prod.yml
Labels: feat

#21 refactor : change table name
  EnF/src/main/java/com/enf/entity/RoleEntity.java
  EnF/src/main/java/com/enf/entity/UserEntity.java
  EnF/src/main/resources/application-dev.yml
Labels: refactor

#22 [feat] 회원 가입 후 사용자 추가 정보 저장을 위한 API 구현
  EnF/src/main/java/com/enf/controller/UserController.java
  EnF/src/main/java/com/enf/entity/BirdEntity.java
  EnF/src/main/java/com/enf/entity/CategoryEntity.java
  EnF/src/main/java/com/enf/entity/UserEntity.java
  EnF/src/main/java/com/enf/model/dto/request/user/AdditionalInfoDTO.java
  EnF/src/main/java/com/enf/model/dto/request/user/UserCategoryDTO.java
  EnF/src/main/java/com/enf/model/type/FailedResultType.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/repository/BirdRepository.java
  EnF/src/main/java/com/enf/repository/CategoryRepository.java
  EnF/src/main/java/com/enf/repository/RoleRepository.java
  EnF/src/main/java/com/enf/repository/UserRepository.java
  EnF/src/main/java/com/enf/service/UserService.java
  EnF/src/main/java/com/enf/service/impl/UserServiceImpl.java
Labels: feat

#25 [feat] 사용자 정보 조회 API 구현
  EnF/src/main/java/com/enf/controller/UserController.java
  EnF/src/main/java/com/enf/model/dto/request/user/UserCategoryDTO.java
  EnF/src/main/java/com/enf/model/dto/response/user/UserInfoDTO.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/service/UserService.java
  EnF/src/main/java/com/enf/service/impl/UserServiceImpl.java
Labels: feat

#27 [feat] 회원정보 수정 API 구현
  EnF/src/main/java/com/enf/controller/UserController.java
  EnF/src/main/java/com/enf/model/dto/request/user/UpdateNicknameDTO.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/repository/UserRepository.java
  EnF/src/main/java/com/enf/service/UserService.java
  EnF/src/main/java/com/enf/service/impl/UserServiceImpl.java
Labels: feat

#29 Feat/#23/token auth
  EnF/build.gradle
  EnF/src/main/java/com/enf/component/UserAccessHandler.java
  EnF/src/main/java/com/enf/component/token/HttpCookieUtil.java
  EnF/src/main/java/com/enf/component/token/JwtUtil.java
  EnF/src/main/java/com/enf/component/token/TokenProvider.java
  EnF/src/main/java/com/enf/config/JwtTokenFilter.java
  EnF/src/main/java/com/enf/config/SecurityConfig.java
  EnF/src/main/java/com/enf/config/SecurityConstants.java
  EnF/src/main/java/com/enf/controller/AuthController.java
  EnF/src/main/java/com/enf/entity/UserEntity.java
  EnF/src/main/java/com/enf/model/dto/auth/AuthTokenDTO.java
  EnF/src/main/java/com/enf/model/dto/auth/UserDetailsDTO.java
  EnF/src/main/java/com/enf/model/dto/request/auth/KakaoUserDetailsDTO.java
  EnF/src/main/java/com/enf/model/type/ConstantsType.java
  EnF/src/main/java/com/enf/model/type/FailedResultType.java
  EnF/src/main/java/com/enf/model/type/SuccessResultType.java
  EnF/src/main/java/com/enf/model/type/TokenType.java
  EnF/src/main/java/com/enf/repository/RoleRepository.java
  EnF/src/main/java/com/enf/repository/UserRepository.java
  EnF/src/main/java/com/enf/service/AuthService.java
  EnF/src/main/java/com/enf/service/impl/AuthServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/UserServiceImpl.java
  EnF/src/main/resources/application-dev.yml
  EnF/src/main/resources/application-prod.yml
  EnF/src/test/java/com/enf/auth/AuthServiceImplTest.java
Labels: feat

#33 [chore] docker-compose.yml redis 추가
  docker-compose.yml
Labels: chore

#35 [feat] 편지 전송(청년층) 로직 추가 및 수정
  EnF/src/main/java/com/enf/component/facade/LetterFacade.java
  EnF/src/main/java/com/enf/component/facade/UserFacade.java
  EnF/src/main/java/com/enf/entity/NotificationEntity.java
  EnF/src/main/java/com/enf/entity/QuotaEntity.java
  EnF/src/main/java/com/enf/model/dto/request/letter/SendLetterDTO.java
  EnF/src/main/java/com/enf/model/dto/request/notification/NotificationDTO.java
  EnF/src/main/java/com/enf/repository/NotificationRepository.java
  EnF/src/main/java/com/enf/repository/QuotaRepository.java
  EnF/src/main/java/com/enf/repository/querydsl/UserQueryRepository.java
  EnF/src/main/java/com/enf/service/impl/LetterServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/NotificationServiceImpl.java
  EnF/src/main/java/com/enf/service/impl/UserServiceImpl.java
Labels: feat, refactor
